# Generated by Django 5.1 on 2025-03-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Posts', '0004_alter_blogpost_dislikes_alter_blogpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='dislikes',
        ),
    ]
