# Generated by Django 5.1 on 2025-03-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
