# Generated by Django 5.1 on 2025-04-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Services', '0003_companyservice_short_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='explanation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
