# Generated by Django 5.1 on 2025-03-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
