# Generated by Django 5.1 on 2025-03-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Posts', '0003_blogpost_dislikes_blogpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
