# Generated by Django 5.1 on 2025-03-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Posts', '0005_remove_blogpost_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='short_title',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
