# Generated by Django 5.1 on 2025-04-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Posts', '0006_blogpost_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.SlugField(editable=False, max_length=60, primary_key=True, serialize=False, unique=True),
        ),
    ]
