# Generated by Django 5.1 on 2025-03-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0002_alter_library_library_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
