# Generated by Django 5.1 on 2025-03-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0003_alter_library_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='coppy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
