# Generated by Django 5.1 on 2025-03-27 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0004_library_coppy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='coppy',
            new_name='copy',
        ),
    ]
