# Generated by Django 5.1 on 2025-03-27 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0005_rename_coppy_library_copy'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libraries', to='categories.librarycategory'),
        ),
        migrations.AddField(
            model_name='library',
            name='short_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
