# Generated by Django 5.2.7 on 2025-10-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0009_resourcerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='view',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
