# Generated by Django 5.2.7 on 2025-10-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0010_library_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='view',
        ),
        migrations.AddField(
            model_name='library',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
