# Generated by Django 5.2.7 on 2025-10-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0011_remove_library_view_library_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcesPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, default='admin@gmail.com', max_length=100)),
                ('number', models.CharField(blank=True, default='01736008374', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
