# Generated by Django 5.2.7 on 2025-10-18 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0012_resourcespublisher_library_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resources.resourcespublisher'),
        ),
    ]
