# Generated by Django 5.2.7 on 2025-10-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Enter a valid email address for subscription', max_length=254, unique=True, verbose_name='Email Address')),
                ('subject', models.CharField(help_text="Brief description of what they're subscribing to", max_length=255, verbose_name='Subscription Subject')),
                ('subscriber_name', models.CharField(default='Not Provided', help_text='Name of the subscriber (optional)', max_length=100, verbose_name='Subscriber Name')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is active', verbose_name='Active Subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='subscriptio_email_d7da7f_idx'), models.Index(fields=['created_at'], name='subscriptio_created_117b3d_idx'), models.Index(fields=['is_active'], name='subscriptio_is_acti_eff6c4_idx')],
            },
        ),
    ]
