# Generated by Django 5.2.7 on 2025-11-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=20)),
                ('sender_mail', models.EmailField(max_length=254)),
                ('sender_phone', models.IntegerField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
