# Generated by Django 5.2.7 on 2025-11-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sender_phone',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
