# Generated by Django 5.2.7 on 2025-11-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_contact_sender_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
