# Generated by Django 5.2.7 on 2025-11-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_contact_sender_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='about',
        ),
    ]
