# Generated by Django 5.1 on 2025-03-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='library_link',
            field=models.TextField(max_length=500),
        ),
    ]
