# Generated by Django 5.1 on 2025-03-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0006_library_category_library_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='short_title',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
